### ISSUE TITLE
Settings Travis CI 

### ISSUE THREAD

**Issue by tyankatsu0105** [gridsome/gridsome-helper-json#1]
# Summary
I want to publish used by Travis CI.

# Detail
I have authority for setting Travis CI.
But, I don't know Gridsome's `NPM_MAIL` and `NPM_TOKEN`.
So, Please set them 🙏

**Comment by tyankatsu0105** [comment]
@hjvedvik 
Please heeeeeelp !!!

**Comment by hjvedvik** [comment]
I have added the env variables in Travis CI now. You can check if it works :)

**Comment by tyankatsu0105** [comment]
@hjvedvik 
Thanks!
I will try deploy cuz this PR #3  was merged

**Comment by hjvedvik** [comment]
Looks like Travis CI gets notified. But you might have to add me as a contributor for `gridsome-helper-json` on npm before it can publish the package.

**Comment by tyankatsu0105** [comment]
Oops! OK. I will add you!

**Comment by tyankatsu0105** [comment]
@hjvedvik 
Oh no... It seems error again.
Could you run command `yarn release:patch` ?

**Comment by hjvedvik** [comment]
Maybe I don't have permissions to publish? I can't see my user on the list of collaborators.

**Comment by tyankatsu0105** [comment]
Sorry I misunderstood maintainers and collaborators.
And it seems succeed !!
I runned this command`npm owner add hjvedvik gridsome-helper-json`.
I should not forget this process...

@hjvedvik thanks for your advice !!
